trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true
    architecture: 'x64'
- script: |
    cd s
    git clone https://github.com/Caleb-R-S/external-code-validation.git pipelines/external-code-validation
  displayName: 'Clone External Code Validation Tools'
- script: |
    pip install -r pipelines/external-code-validation/requirements.txt
    python pipelines/external-code-validation/index.py
  displayName: 'Run External Code Validation'
